services:
  mysql:
    image: mysql:8.0
    container_name: future-vault-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: future_vault

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 40s

  app:
    build: .
    container_name: future-vault-app

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/future_vault
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

volumes:
  mysql-data: